# Link to API docs: https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  criSocket: "unix:///run/containerd/containerd.sock"
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{ hostvars[groups['control-plane'][0]]['ansible_default_ipv4']['address'] }}:6443"
    token: "{{ token }}"
    caCertHashes:
      - "{{ cert_hash }}"
