---
- hosts: control-plane
  name: "Copy kubeconfig from remote"
  tasks:
    - name: fetching
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ../admin.conf
        flat: yes
      run_once: True
